api_platform:
    title: Semaine Challenge 1
    version: 1.0.0
    # Mercure integration, remove if unwanted
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    patch_formats:
        json: ["application/merge-patch+json"]
        jsonapi: ["application/vnd.api+json"]
    enable_swagger: true
    enable_swagger_ui: true
    enable_docs: false
    enable_entrypoint: false
    mercure:
        enabled: false
