name: 💻 Deploy to dev

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 💾 Update database credentials
        env: 
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_DEV }}
          DB_USER: ${{ secrets.DB_USER_DEV }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
        run: |
          sed -i "s#DATABASE_URL=.*#DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:5432/$DB_NAME?serverVersion=13&charset=utf8#g" api/.env
          sed -i "s#APP_ENV=.*#APP_ENV=dev#g" api/.env
      - name: 📤 Upload to [dev] server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './api/'
          server-dir: '/api/dev/'
          delete_remote: false
      
          
